"""added email to user

Revision ID: 56316719682f
Revises: f25eaf42d16b
Create Date: 2023-01-17 19:41:20.957571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56316719682f'
down_revision = 'f25eaf42d16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    # ### end Alembic commands ###
